name: codepen CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository 
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v1
      with: 
        node-version: 14.x
    - name: Deploy to github pages
      uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1